name: one-pipe
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "Fisrt Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Fisrt Action"
        run: echo "Hello World"
      - name: "Second Action"
        run: |
          echo "Fisrt workflow created"
          echo "Congratulations"
      - name: "Shell Python"
        run: |
          variavel = "Hello World again"
          print(variavel)
        shell: python
  second-job:
      name: "Second Job"
      runs-on: ubuntu-latest
      needs: [first-job]
      steps:
        - name: "Verify Node version"
          run: node --version
        - name: "Update Node to 22.15.0"
          uses: actions/setup-node@v4
          with:
            node-version: 22.15.0
        - name: "Verify Node version again"
          run: node --version
